// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA20Tr-1voZqdbmNIYvsglfexUXNHoLBGw',
    appId: '1:842107455276:web:5c73f83272fe92ab8dce89',
    messagingSenderId: '842107455276',
    projectId: 'flutter-test-61e5e',
    authDomain: 'flutter-test-61e5e.firebaseapp.com',
    storageBucket: 'flutter-test-61e5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTO1f1a4n6t9CC2I3LhbWw9nUfWWf9gsc',
    appId: '1:842107455276:android:22b04079d6d647cb8dce89',
    messagingSenderId: '842107455276',
    projectId: 'flutter-test-61e5e',
    storageBucket: 'flutter-test-61e5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8ELGfiP9U3_alpe0pIxtZ2uzk-ZHlGs',
    appId: '1:842107455276:ios:3d7caf0172b5a5648dce89',
    messagingSenderId: '842107455276',
    projectId: 'flutter-test-61e5e',
    storageBucket: 'flutter-test-61e5e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8ELGfiP9U3_alpe0pIxtZ2uzk-ZHlGs',
    appId: '1:842107455276:ios:3d7caf0172b5a5648dce89',
    messagingSenderId: '842107455276',
    projectId: 'flutter-test-61e5e',
    storageBucket: 'flutter-test-61e5e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
